### ISSUE TITLE
Pheobe 0.31a Input format not defined.

### ISSUE THREAD

**Issue by selseyastro** [phoebe-project/phoebe1#12]
I have managed to load pheobe 0.31a onto my Win10 PC.  However, every time I try to load a light curve it just says it cannot find the file or incorrect format.
I have tried csv, text, tab separated, space separated etc. Just a normal light curve:
BJD,Vmag
two columns.

There does not seem to be any help as to format of the input file. except that # is a comment.
I have even tried to load a file from the Data folder.
UVLeo.b
Cannot load or plot that light curve.
Thanks  for your help.
Regards
John
Altair Eclipsing Binary Science Research Group 
MRAS

**Comment by kecnry** [comment]
Hi John - thanks for reporting this issue.  I just transferred it to the phoebe1 repository since it seems specific to version 0.31.

**Comment by aprsa** [comment]
It seems that you are trying to load data files by File->Open instead of adding them in the Data tab. PHOEBE stores its parameters in text files (usually with .phb or .phoebe extensions) and these are key=value pairs. That's what's expected when you open a file. To add a dataset, click on the Add button in the Data tab, LC data frame. Click on the Filename in the dialog window and provide your input data there. The format is whitespace-separated set of 2 or 3 columns which you also define in the dialog window.
